---

- hosts: dev 
  become: true
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 7200
        
    - name: Install all required APT packages
      apt:
        name:
          - python3-pip
          - snmpd
          - prometheus-node-exporter
        state: latest

    - name: Install all required Python packages via pip
      pip:
        executable: pip3
        name:
          - flask
          - gunicorn
        state: latest

    - name: Copy Flask application
      copy:
        src: python_files/service.py
        dest: /home/ubuntu/app.py
        owner: ubuntu
        mode: '0644'
        
    - name: copy snmpd.conf file
      copy: 
        src: ./templates/snmpd.conf 
        dest: /etc/snmp/snmpd.conf

    - name: Deploy Flask application with Gunicorn
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 app:app
      args:
        chdir: /home/ubuntu

    - name: restart snmpd
      service:
        name: snmpd
        state: restarted
    
    
- hosts: all
  gather_facts: true
    
- hosts: HAproxy
  become: true
  gather_facts: no
  tasks: 
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 7200

    - name: Installing requird packages
      apt:
        name: 
          - haproxy
          - nginx
          - snmp 
          - snmp-mibs-downloader
          - keepalived
          - prometheus-node-exporter
        state: present
   
    - name: Template keepalived config
      template:
        src: ./templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf

    - name: copy template haproxy 
      template: 
        src: ./templates/haproxy.conf
        dest: /etc/haproxy/haproxy.cfg

    - name: copy template nginx 
      template: 
        src: ./templates/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted


- hosts: bastion
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 7200

    - name: Install all required APT packages
      apt:
        name:
          - prometheus
          - prometheus-node-exporter
        state: latest

    - name: copy prometheus.yml file
      template: 
        src: ./templates/prometheus.yaml
        dest: /etc/prometheus/prometheus.yml

    - name: Restart Prometheus
      service:
        name: prometheus
        state: restarted
