---
- hosts: all 
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
    - name: updating all hosts 
      apt:
        update_cache: yes
    - name : sudo wait
      become: yes
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- hosts: webservers 
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: update all webservers 
      apt:
        update_cache: true

    - name: Installing nginx
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: pip install
      apt:
        name: python3-pip
        state: latest
        update_cache: true

    - name: Installing flask app
      pip:
        executable: pip3
        name: flask